
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <link type="text/css" rel="stylesheet" href="/fonts/opensans.css">
    <link rel="stylesheet" href="/css/font-awesome.css">
    <link rel=icon href="/logo/logo_KK_2015_v13.png">
    <link href="/css/main.css" charset="UTF-8" rel="stylesheet" type="text/css">
    <link href="/css/admin_page.css" charset="UTF-8" rel="stylesheet" type="text/css">
    <link href="/css/bootstrap.css" charset="UTF-8" rel="stylesheet" type="text/css"><link href='/css/index.css' charset='UTF-8' rel='stylesheet' type='text/css'>    <script src="/js/jquery-2.2.3.min.js" charset="utf-8"></script><script src='/js/Windows.js' charset='utf-8'></script><script src='/js/index.js' charset='utf-8'></script><script src='/js/main.js' charset='utf-8'></script>    <title>Киностудия "KINOKRUT LABORATORY"</title>
    <style>
        body
        {
            padding-bottom:400px
        }
    </style>
</head>
<body>
<div id="header">
    <header>
        <img src="/logo/logo_KK_2015_v13.png">
        <nav>
            <a class="header_link">Портфолио</a>
            <a class="header_link" href="/public%20html/Employees.html">О нас</a>
            <a class="header_link" href="/index.php#comment-ribbon">Отзывы</a>
            <a class="header_link" href=#footer>Контакты</a>
            <a class="header_link" href="/public%20html/Private_office.php">Личный кабинет</a>
            <a id="icon-checking" class="fa fa-sign-in fa-2x header_link"></a>
        </nav>
        <div ID="triangle_container">
            <div id="Window">
                <form>
                    <caption>Вход в личный кабинет</caption>
                    <table>
                        <tr>
                            <td colspan="2"></td>
                            <input type="text" placeholder="Логин"></tr>
                        <tr>
                            <td colspan="2"></td>
                            <input type="text" placeholder="Пароль"></tr>
                        <tr>
                            <td><input class="btn btn-default btn-sm" type="submit" value="Войти" id="Ent"></td>
                            <td><input class="btn btn-default btn-sm" id="Reg" type="button" value="Регистрация"
                                       onclick="toRegPage()"></td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </header>
</div>
<div id="bordered-shadow">
    <div id="wrapper">
        <h1>Добрый день, уважаемый администратор</h1>
        <h3>На текущей странице вы можете просмотреть количество зарегистрированных пользователей, а также количество всех сделанных заказов за текущий месяц</h3>
        <div id="report-container">
            <form id="report-header" class="row">
                <span id="month-header" class="col-lg-6">Выберите период построения отчета</span>
                <select id="month-select" class="col-lg-4 col-lg-offset-2 form-control">
                    <option>Январь</option>
                    <option>Февраль</option>
                    <option>Март</option>
                    <option>Апрель</option>
                    <option>Май</option>
                    <option>Июнь</option>
                    <option>Июль</option>
                    <option>Август</option>
                    <option>Сентябрь</option>
                    <option>Октябрь</option>
                    <option>Ноябрь</option>
                    <option>Декабрь</option>
                </select>
            </form>
            <div id="report-body" class="row">
                <h4 class="col-lg-7 col-lg-offset-3">Количество пользователей в системе: 75</h4>
                <h4 class="col-lg-7 col-lg-offset-3">Количество сделанных заказов в системе: 50</h4>
                <h4 class="col-lg-7 col-lg-offset-3">Количество выполненных входов в систему: 263</h4>
            </div>
        </div>
</div>
<footer>
    <div id="footer">
        <p>Наши контакты:</p>

        <ul>
            <li class="fa fa-phone" aria-hidden="true"> 8 (917) 221-28-32
            <li class="fa fa-envelope-o" aria-hidden="true"> info@kinokrut.com
            <li class="fa fa-map-marker" aria-hidden="true"> г. Казань, ул. Дементьева, д. 70а
            <li id=name>Компания «Kinokrut Laboratory»</li>
        </ul>
        <nav id="scl">
            <a href="https://vk.com/kinokrutlaboratory" id=VKlink target="_blank"></a>
            <a href="https://https://www.facebook.com/Kinokrut-Laboratory-1541593912735386/" id=FBlink
               target="_blank"></a>
            <a href="https://www.instagram.com/kinokrut_laboratory/" id=INSTlink target="_blank"></a>
            <a href="https://www.youtube.com/user/kinokrutkazan" id=YTlink target="_blank"></a>
        </nav>
        <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2239.0607734676496!2d49.10462331546061!3d55.861611980582616!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x41594d7219e4d9c1%3A0x291e7a0c04cb2c19!2zedC70LjRhtCwINCU0LXQvNC10L3RgtGM0LXQstCwLCA3MNCQLCDQmtCw0LfQsNC90YwsINCg0LXRgdC_LiDQotCw0YLQsNGA0YHRgtCw0L0sIDQyMDEyNw!5e0!3m2!1sru!2sru!4v1460894543641"
            frameborder="0" style="border:0" allowfullscreen></iframe>

        <address>
            &copy; Компания «Kinokrut Laboratory», Казань 2016 г.
        </address>
    </div>
</footer>
</body>
</html>