<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <link type="text/css" rel="stylesheet" href="/fonts/opensans.css">
    <link rel="stylesheet" href="/css/font-awesome.css">
    <link rel=icon href="/logo/logo_KK_2015_v13.png">
    <link href="/css/bootstrap.css" charset="UTF-8" rel="stylesheet" type="text/css">
    <link href="/css/Private_office.css" charset="UTF-8" rel="stylesheet" type="text/css">
    <link href="/css/main.css" charset="UTF-8" rel="stylesheet" type="text/css">
    <link href="/css/addressField.css" charset="UTF-8" rel="stylesheet" type="text/css">
    <link href='/css/index.css' charset='UTF-8' rel='stylesheet' type='text/css'>
    <script src="/js/jquery-2.2.3.min.js" charset="utf-8"></script>
    <script src='/js/Windows.js' charset='utf-8'></script>
    <script src='/js/index.js' charset='utf-8'></script>
    <script src='/js/bootstrap.js' charset='utf-8'></script>
    <script src='/js/index.js' charset='utf-8'></script>
    <title>Киностудия "KINOKRUT LABORATORY"</title>
</head>
<body>
<div id="header">
    <header>
        <img src="/logo/logo_KK_2015_v13.png">
        <nav>
            <a class="header_link">Портфолио</a>
            <a class="header_link" href="/public%20html/Employees.html">О нас</a>
            <a class="header_link" href="/index.php#comment-ribbon">Отзывы</a>
            <a class="header_link" href=#footer>Контакты</a>
            <a class="header_link">Личный кабинет</a>
            <a id="icon-checking" class="fa fa-sign-in fa-2x header_link"></a>
        </nav>
        <div ID="triangle_container">
            <div id="Window">
                <form>
                    <caption>Вход в личный кабинет</caption>
                    <table>
                        <tr>
                            <td colspan="2"></td>
                            <input type="text" placeholder="Логин"></tr>
                        <tr>
                            <td colspan="2"></td>
                            <input type="text" placeholder="Пароль"></tr>
                        <tr>
                            <td><input class="btn btn-default btn-sm" type="submit" value="Войти" id="Ent"></td>
                            <td><input class="btn btn-default btn-sm" id="Reg" type="button" value="Регистрация"
                                       onclick="toRegPage()"></td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </header>
</div>


<div id="wrapper">
    <h1>Здравствуйте, Дмитрий</h1>

    <h2>Здесь вы можете выбрать интересующие вас настройки: сменить учетные данные и просмотреть сделанные заказы</h2>

    <div class="row container-row">
        <ul class="nav nav-pills nav-tabs-justified row" role="tablist">
            <li role="presentation" class="active col-lg-3 col-lg-offset-3"><a href="#Private_data" aria-controls="home" role="tab"
                                                      data-toggle="tab">Учетные данные</a></li>
            <li role="presentation" class="col-lg-3"><a href="#Orders" aria-controls="profile" role="tab" data-toggle="tab">Оформленные
                    заказы</a></li>
        </ul>
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane fade in active" id="Private_data">
                <div class="row">
                    <form class="col-lg-12">
                        <div class="row">
                            <label class="col-lg-2 col-lg-offset-3">Ваше имя</label>
                            <input class="col-lg-2 col-lg-offset-1"
                                                                           type="text">
                        </div>
                        <div class="row">
                            <label class="col-lg-2 col-lg-offset-3">Ваше фамилия</label>
                            <input
                                class="col-lg-2 col-lg-offset-1" type="text">
                        </div>
                        <div class="row">
                            <label class="col-lg-2 col-lg-offset-3">Ваше отчество</label>
                            <input
                                class="col-lg-2 col-lg-offset-1"
                                type="text">
                        </div>
                        <div class="row">
                            <label class="col-lg-2 col-lg-offset-3">Ваш телефон</label>
                            <input
                                class="col-lg-2 col-lg-offset-1" type="text">
                        </div>
                        <div class="row">
                            <label class="col-lg-2 col-lg-offset-3">Ваша дата рождения</label>
                            <input
                                class="col-lg-2 col-lg-offset-1"
                                type="text">
                        </div>
                        <div class="row">
                            <label class="col-lg-2 col-lg-offset-3">Ваш логин</label>
                            <input
                                class="col-lg-2 col-lg-offset-1" type="text">
                        </div>
                        <div class="row">
                            <label class="col-lg-2 col-lg-offset-3">Ваше пароль</label>
                            <input
                                class="col-lg-2 col-lg-offset-1" type="text">
                        </div>
                        <div class="row">
                            <label class="col-lg-2 col-lg-offset-3">Ваше e-mail</label>
                            <input
                                class="col-lg-2 col-lg-offset-1" type="text">
                        </div>
                        <div class="row"><input type="submit" class="btn-success col-lg-4 col-lg-offset-4" value="Обновить"/></div>
                    </form>
                </div>
            </div>
            <div role="tabpanel" class="tab-pane fade" id="Orders">
                <table class="table table-hover table-bordered">
                    <tr>
                        <td>Номер заказа</td>
                        <td>Сумма заказа</td>
                        <td>Описание заказа</td>
                    </tr>
                    <tr>
                        <td>0000052365</td>
                        <td>4500</td>
                        <td>Съемка на улице</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>


<address>
    &copy; Компания «Kinokrut Laboratory», Казань 2016 г.
</address>
</body>
</html>