<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <link type="text/css" rel="stylesheet" href="/fonts/opensans.css">
    <link rel="stylesheet" href="/css/font-awesome.css">
    <link rel=icon href="/logo/logo_KK_2015_v13.png">
    <link href="/css/main.css" charset="UTF-8" rel="stylesheet" type="text/css">
    <link href="/css/bootstrap.css" charset="UTF-8" rel="stylesheet" type="text/css">
    <link href='/css/index.css' charset='UTF-8' rel='stylesheet' type='text/css'>
    <script src="/js/jquery-2.2.3.min.js" charset="utf-8"></script>
    <script src="/js/bootstrap.js" charset="utf-8"></script>
    <script src='/js/Windows.js' charset='utf-8'></script>
    <script src='/js/index.js' charset='utf-8'></script>
    <script src='/js/main.js' charset='utf-8'></script>
    <title>Киностудия "KINOKRUT LABORATORY"</title>
    <style>
        body {
            padding-bottom: 400px
        }
    </style>
</head>
<body>
<div id="header">
    <header>
        <img src="/logo/logo_KK_2015_v13.png">
        <nav>
            <a class="header_link">Портфолио</a>
            <a class="header_link" href="/public%20html/Employees.html">О нас</a>
            <a class="header_link" href="/index.php#comment-ribbon">Отзывы</a>
            <a class="header_link" href=#footer>Контакты</a>
            <a class="header_link" href="/public%20html/Private_office.php">Личный кабинет</a><a id='icon-checking'
                                                                                                 class='fa fa-sign-in fa-2x header_link'></a>
        </nav>
        <div ID="triangle_container">
            <div id="Window">
                <form>
                    <caption>Вход в личный кабинет</caption>
                    <table>
                        <tr>
                            <td colspan="2"></td>
                            <input type="text" placeholder="Логин"></tr>
                        <tr>
                            <td colspan="2"></td>
                            <input type="text" placeholder="Пароль"></tr>
                        <tr>
                            <td><input class="btn btn-default btn-sm" type="submit" value="Войти" id="Ent"></td>
                            <td><input class="btn btn-default btn-sm" id="Reg" type="button" value="Регистрация"
                                       onclick="toRegPage()"></td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </header>
</div>
<div id="bordered-shadow">
    <div id="wrapper">
        <div id="title-block"><H1>У нас можно заказать:</H1>
            <img class="service_img" src="/img/13-resized.jpg" width="586px" height="450px">
            <ul id="descr">
                <li><a href="/public%20html/Video_portfolio.html">Видеосъёмка документальных и художественных
                        фильмов.</a>
                </li>
                <li><a href="/public%20html/Video_portfolio.html">Монтаж, спец.эффекты, 2D и 3D графика и т.д.</a>
                </li>
                <li><a href="/public%20html/Video_portfolio.html">Создание рекламы, корпоративных фильмов, клипов и
                        всевозможных креативных роликов под ключ.</a></li>
                <li><a href="/public%20html/Rent_of_equipment.html">Аренда оборудования и видеосъёмка на Red
                        Scarlet,
                        аэросъемка на Dji Inspire.</a></li>
                <li><a href="/public%20html/Video_portfolio.html">Видео конференций, семинаров и мероприятий.</a>
                </li>
                <li><a href="/public%20html/Photo_portfolio.html">Фото различных мероприятий.</a></li>
                <li><a href="/public%20html/Rent_apartment.html">Аренда павильона Kinokrut Laboratory общей площадью
                        260
                        м.</a></li>
            </ul>
        </div>
        <h2 class="portfolio-header">Профессиональная фотосъемка</h2>

        <div class="portfolio-content">
            <div style="float: left" class="portfolio">
                <ul>
                    <li><img src="/img/Фото%20портфолио/GUM-7969.jpg"/></li>
                    <li><img src="/img/Фото%20портфолио/GUM-7941.jpg"/></li>
                    <li><img src="/img/Фото%20портфолио/GUM-8010.jpg"/></li>
                    <li><img src="/img/Фото%20портфолио/GUM-8266.jpg"/></li>
                    <li><img src="/img/Фото%20портфолио/GUM-8255.jpg"/></li>
                    <li><img src="/img/Фото%20портфолио/GUM-7906.jpg"/></li>
                    <li><img src="/img/Фото%20портфолио/GUM-7920.jpg"/></li>
                    <li><img src="/img/Фото%20портфолио/GUM-7969.jpg"/></li>
                </ul>
            </div>
            <p class="right-sided">
                Фотоагентство «10-22mm» - это объединение опытных фотографов, работающих в области архитектурной,
                строительной, производственной, промышленной, интерьерной и высотной фотосъемки.
                <br/>
                Наша основная задача – радовать своих клиентов качественными фотографиями.
            </p>
            <a href="/public%20html/Photo_portfolio.html" class="to-portfolio right-sided">Подробнее</a>
        </div>
        <div class="portfolio-content">
            <img src="/img/Буфер%20обмена01.jpg" style="float: right" class="portfolio" onclick="toVimio()"/>

            <p class="left-sided">
                Современная фототехника в совокупности с профессионализмом наших сотрудников позволяют делать
                безупречные
                фотографии в независимости от места и условий съемок.
                <br/>
                Мы всегда готовы предложить своим клиентам оригинальные решения по привлекательным ценам.
                <br/>
                Будьте уверены, творческие плоды фотоагентства «10-22mm» всегда будут в тренде.
            </p>
            <a href="https://vimeo.com/kinokrut" class="to-portfolio left-sided">Подробнее</a>
        </div>
        <h2 class="portfolio-header">Аренда павильона и оборудования</h2>

        <div class="portfolio-content">
            <div style="float: left" class="portfolio">
                <ul>
                    <li><img src="/img/13-resized.jpg"/></li>
                    <li><img src="/img/fstudio_fstudio.jpg"/></li>
                    <li><img src="/img/photostudio_03.jpg"/></li>
                    <li><img src="/img/fstudio_fstudio.jpg"/></li>
                    <li><img src="/img/13-resized.jpg"/></li>
                </ul>
            </div>
            <p class="right-sided">
                Описание портфолио....
            </p>
            <a href="/public%20html/Photo_portfolio.html" class="to-portfolio right-sided">Подробнее</a>
        </div>
        <div class="portfolio-content">
            <div style="float: right" class="portfolio">
                <ul>
                    <li><img src="/img/Оборудование/lumix_fz1000_noir.jpg"/></li>
                    <li><img src="/img/Оборудование/large_inspire_p1.jpg"/></li>
                    <li><img src="/img/Оборудование/DJI-Osmo-hardware.jpg"/></li>
                    <li><img src="/img/Оборудование/Red%20Scarlet.jpg"/></li>
                    <li><img src="/img/Оборудование/lumix_fz1000_noir.jpg"/></li>
                </ul>
            </div>
            <p class="left-sided">
                Описание портфолио....
            </p>
            <a href="/public%20html/Video_portfolio.html" class="to-portfolio left-sided">Подробнее</a>
        </div>
    </div>
    <div id="comment-ribbon">
        <ul>
            <li class="comment">
                <div class="comment">
                    <p>В качестве фотографа решили воспользоваться услугами Kinokrut Laboratory. Очень понравилось
                        ваше
                        отношение
                        к работе - умеете заставить улыбнуться. Ни одно интересное событие на мероприятии не
                        осталось не
                        запечатленным. Спасибо вам большое! Фотографии супер, все участники довольны!</p>
                    <img src="/img/comments/pers8.jpg"/>
                </div>
            </li>
            <li class="comment">
                <div class="comment">
                    <p>Открытие всероссийского форума! Такой волнительный день! Столько эмоций! И все эти эмоции так
                        здорово
                        были запечатлены на
                        фотографиях! Их стооооолькооооо... Все еще не успели посмотреть,но то что смотрели - не
                        выразить
                        словами, просто класс! Спасибо за день, за работу, прекрасные эмоции!</p>
                    <img src="/img/comments/pers7.jpg"/>
                </div>
            </li>
            <li class="comment">
                <div class="comment">
                    <p>К студии "Kinokrut Laboratory" у меня особое отношение, оно более семейное, потому что эта
                        команда
                        сопровождает меня в роли профессионалов фотографии и настоящих друзей уже на протяжении
                        многих лет и
                        многих важных событий. Фотографии и видео превзошли все наши ожидания.</p>
                    <img src="/img/comments/pers10.jpg"/>
                </div>
            </li>
            <li class="comment">
                <div class="comment">
                    <p>Огромное спасибо за съемку! Уж насколько мы в этот день были как два бревна, по
                        фотографиям об этом никто не догадался. Все остались в полном восторге от твоей работы - и
                        всем интересующимся я уже скинула координаты.
                    </p>
                    <img src="/img/comments/pers4.jpg"/>
                </div>
            </li>
            <li class="comment">
                <div class="comment">
                    <p>Хочу поблагодарить вас за прекрасные фотографии, от которых все гости на
                        банкете были просто в восторге! Очень хорошо получились снимки, и идея сняться в музее
                        соц.быта.
                    </p>
                    <img src="/img/comments/pers5.jpg"/>
                </div>
            </li>
            <li class="comment">
                <div class="comment">
                    <p>В качестве фотографа решили воспользоваться услугами Kinokrut Laboratory. Очень понравилось
                        ваше
                        отношение
                        к работе - умеете заставить улыбнуться. Ни одно интересное событие на мероприятии не
                        осталось не
                        запечатленным. Спасибо вам большое! Фотографии супер, все родственники довольны!</p>
                    <img src="/img/comments/pers8.jpg"/>
                </div>
            </li>
            <li class="comment">
                <div class="comment">
                    <p>Открытие всероссийского форума! Такой волнительный день! Столько эмоций! И все эти эмоции так
                        здорово
                        были запечатлены на
                        фотографиях! Их стооооолькооооо... Все еще не успели посмотреть,но то что смотрели - не
                        выразить
                        словами, просто класс! Спасибо за день, за работу, прекрасные эмоции!</p>
                    <img src="/img/comments/pers7.jpg"/>
                </div>
            </li>
        </ul>
    </div>
    <div id="button-panel">
        <button id="more-comments">Еще комментарий</button>
        <button id="add-comment" data-toggle="modal" data-target="#myModal">Добавить комментарий</button>
    </div>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Введите ваш комментарий</h4>
                </div>
                <div class="modal-body">
                    <textarea id="modal-comment">

                    </textarea>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                    <button id="publish-button" type="button" class="btn btn-primary">Опубликовать</button>
                </div>
            </div>
        </div>
    </div>
</div>
<footer>
    <div id="footer">
        <p>Наши контакты:</p>

        <ul>
            <li class="fa fa-phone" aria-hidden="true"> 8 (917) 221-28-32
            <li class="fa fa-envelope-o" aria-hidden="true"> info@kinokrut.com
            <li class="fa fa-map-marker" aria-hidden="true"> г. Казань, ул. Дементьева, д. 70а
            <li id=name>Компания «Kinokrut Laboratory»</li>
        </ul>
        <nav id="scl">
            <a href="https://vk.com/kinokrutlaboratory" id=VKlink target="_blank"></a>
            <a href="https://https://www.facebook.com/Kinokrut-Laboratory-1541593912735386/" id=FBlink
               target="_blank"></a>
            <a href="https://www.instagram.com/kinokrut_laboratory/" id=INSTlink target="_blank"></a>
            <a href="https://www.youtube.com/user/kinokrutkazan" id=YTlink target="_blank"></a>
        </nav>
        <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2239.0607734676496!2d49.10462331546061!3d55.861611980582616!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x41594d7219e4d9c1%3A0x291e7a0c04cb2c19!2zedC70LjRhtCwINCU0LXQvNC10L3RgtGM0LXQstCwLCA3MNCQLCDQmtCw0LfQsNC90YwsINCg0LXRgdC_LiDQotCw0YLQsNGA0YHRgtCw0L0sIDQyMDEyNw!5e0!3m2!1sru!2sru!4v1460894543641"
            frameborder="0" style="border:0" allowfullscreen></iframe>

        <address>
            &copy; Компания «Kinokrut Laboratory», Казань 2016 г.
        </address>
    </div>
</footer>
</body>
</html>